FROM debian:bookworm-slim
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends redsocks iptables iproute2 dnsutils && \
    rm -rf /var/lib/apt/lists/*
COPY docker-redsocks-start.sh /start.sh
RUN chmod +x /start.sh
CMD ["/start.sh"]
